# Copyright (c) 2024, Felipe Neves
# SPDX-License-Identifier: Apache-2.0

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: lkmotor_mf4005_driver

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: lkmotor_mf4005_driver/samples/mf4005_shell
          toolchains: arm-zephyr-eabi

      # - name: Build
      #   run: |
      #     west build -palways -barduino_giga_r1/stm32h747xx/m7 samples/mf4005_shell
