# Copyright (c) 2024, Felipe Neves
# SPDX-License-Identifier: Apache-2.0

name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: zephyrprojectrtos/ci:latest
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: lkmotor_mf4005_driver
      
      - name: Initialize and  Build samples
        working-directory: lkmotor_mf4005_driver
        run: |
          pip3 install west
          west init -l .
          west update
          pip3 install -r ../zephyr/scripts/requirements-base.txt      
          source ../zephyr/zephyr-env.sh
          west build -palways -barduino_giga_r1/stm32h747xx/m7 samples/mf4005_shell
